### ISSUE TITLE
Remove wrapper after all children has unwrapped

### ISSUE THREAD

**Issue by Mukhametvaleev** [benwiley4000/react-dot-fragment#7]
**Suggestion:**
I think we should remove wrapper itself, after all children has been unwrapped

**Problem:**
<img width="275" alt="image" src="https://user-images.githubusercontent.com/8947056/58748494-6369be00-8482-11e9-9029-1987c4415dbf.png">

**Possible solution:**
```javascript
_proto.unwrapChildren = function unwrapChildren() {
    var _this2 = this;

    // defer first to style calculation to ensure CSS transitions can happen:
    // https://stackoverflow.com/a/24195559/4956731
    setTimeout(function () {
      // plain js rocks!
      // https://plainjs.com/javascript/manipulation/unwrap-a-dom-element-35/
      if (!_this2.div.parentNode) {
        return;
      }

      _this2.saveFocusedDescendantElement(_this2.div);

      _this2.orphans = [];

      while (_this2.div.firstChild) {
        _this2.orphans.push(_this2.div.firstChild);

        _this2.div.parentNode.insertBefore(_this2.div.firstChild, _this2.div);
      }

      _this2.restoreFocusedDescendantElement();

      _this2.div.remove();  // <- Something like this
    });
  };
```

**Comment by benwiley4000** [comment]
@Mukhametvaleev I'm sorry for not seeing this issue when you opened it! I've been a bit scattered during the past year and I need to catch up on some of my open source projects. I'd like to solve this one in a way that makes sense.

The main problem with removing the wrapper is that it needs to be there for the next render update - we "re-wrap" the children on each update so React cant still update the content and doesn't get confused, then we unwrap again after the update is completed.

I think we can probably do something similar to what you're suggesting though.

After the unwrap:

```js
this.parentNode = this.div.parentNode;
this.parentNode.removeChild(this.div);
```

And before the re-wrap:

```js
this.parentNode.appendChild(this.div);
```

I would need to test this to make sure it works but I don't see why it wouldn't. If you'd like you can make a PR! Otherwise I can try to get to it soon.

**Comment by benwiley4000** [comment]
I updated the "before re-wrap" code to make sure we re-insert the wrapper div in the correct position (next to the orphans), since it's possible the `parentNode` has other children managed by sibling components to our `Fragment`.

**Comment by benwiley4000** [comment]
cc @albertvision FYI I will try to include a fix for this issue before re-releasing, hopefully in the next couple of days. Let me know if you need #9 shipped sooner.
